server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

spring:
  application:
    name: povsagent

  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano
          temperature: 0.1

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: INFO
    org.springframework.ai: DEBUG
    org.springframework.web: DEBUG